from sklearn import preprocessing
import numpy as np
le = preprocessing.LabelEncoder()
y_train = np.reshape(np.load('./y_train.npy', allow_pickle = True), 1844)
y_test = np.reshape(np.load('./y_test.npy', allow_pickle = True), 791)
le.fit(y_train)
#print(le.classes_)
y_train_label = np.reshape(le.transform(y_train), (1844,1))
y_test_label = np.reshape(le.transform(y_test), (791,1))
#print(y_train_label.shape)
#np.save('y_train_label.npy', y_train_label)
#np.save('y_test_label.npy', y_test_label)
#np.save('y_classes.npy', le.classes_)
X_train = np.load('./X_train_zeros.npy')
print(X_train[125])
